# Generated by Django 5.1.2 on 2024-10-19 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RepairRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=255)),
                ('description_problem', models.TextField()),
                ('preferred_date_time_repair', models.DateTimeField()),
                ('contact_info', models.CharField(max_length=255)),
            ],
        ),
    ]
